import LoggedInEle from '@/components/common/LoggedInEle';
import NotLoggedIn from '@/components/common/NotLoggedIn';
import { useUser } from '@auth0/nextjs-auth0/client';
import Head from 'next/head';
import React from 'react';

export default function Home() {
  const { user } = useUser();
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-2 mt-16 w-full min-h-[calc(100vh-140px)] bg-blue-50">
        {user?.email ? <LoggedInEle user={user} /> : <NotLoggedIn />}
      </main>
    </React.Fragment>
  );
}
