import SearchBar from '@/components/common/SearchBar';
import Head from 'next/head';
import React from 'react';

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-2 mt-16 w-full min-h-[calc(100vh-140px)] bg-blue-50">
        <SearchBar />
      </main>
    </React.Fragment>
  );
}
